// ============================================================
// Draft Template — Bayilik Sözleşmesi
// ============================================================
//
// Türk hukukunda özel olarak düzenlenmemiş, isimsiz sözleşme.
// TBK genel hükümleri + TTK m.18 (basiretli tacir) + 4054
// Rekabet Kanunu + 2002/2 Dikey Anlaşmalar Tebliği + TTK m.122
// (acentelik — portföy tazminatı kıyasen) etkisinde. Avukat
// onayı yerini tutmaz.
//
// Kritik noktalar (plan §8.2 F):
// - Münhasırlık coğrafyası ve konusu net olmalı
// - RPM (yeniden satış fiyat tespiti) 4054 m.4 yasak
// - Portföy tazminatı dışlama maddesi yoksa TTK m.122 kıyasen
//   uygulama riski
// - Belirsiz süreli fesih → makul ihbar süresi
// ============================================================

import type { DraftTemplate } from "../types";

export const DISTRIBUTOR_TEMPLATE: DraftTemplate = {
  id: "distributor",
  label: "Bayilik Sözleşmesi",
  description:
    "Sağlayıcı ile bayi arasındaki bölge, münhasırlık, minimum alım taahhüdü ve ödeme koşullarını içeren dağıtım sözleşmesi.",
  category: "Bayilik",
  iconKey: "handshake",
  estimatedMinutes: 10,
  documentTitle: "BAYİLİK SÖZLEŞMESİ",

  questions: [
    // ── Step 1 — Taraflar ──
    {
      id: "supplier.name",
      step: 1,
      group: "Taraflar",
      label: "Sağlayıcı — Ticari Unvan",
      helpText: "Ürünü sağlayan / üretici taraf. Sicil unvanını girin.",
      type: "text",
      required: true,
    },
    {
      id: "supplier.nameStyle",
      step: 1,
      group: "Taraflar",
      label: "Sağlayıcı — Ticari Unvan Görünümü",
      helpText: "Şirket unvanının sözleşme metninde nasıl görüneceğini seçin.",
      type: "radioGroup",
      required: true,
      defaultValue: "uppercase",
      options: [
        { value: "uppercase", label: "Tamamı büyük harf" },
        { value: "lowercase_bold", label: "Küçük harf ve kalın" },
      ],
    },
    {
      id: "supplier.taxNo",
      step: 1,
      group: "Taraflar",
      label: "Sağlayıcı — Vergi No",
      type: "text",
      required: true,
    },
    {
      id: "supplier.address",
      step: 1,
      group: "Taraflar",
      label: "Sağlayıcı — Adres",
      type: "longText",
      required: true,
    },
    {
      id: "supplier.representative",
      step: 1,
      group: "Taraflar",
      label: "Sağlayıcı — Yetkili Temsilci",
      type: "text",
      required: true,
    },
    {
      id: "dealer.name",
      step: 1,
      group: "Taraflar",
      label: "Bayi — Ticari Unvan",
      type: "text",
      required: true,
    },
    {
      id: "dealer.nameStyle",
      step: 1,
      group: "Taraflar",
      label: "Bayi — Ticari Unvan Görünümü",
      helpText: "Şirket unvanının sözleşme metninde nasıl görüneceğini seçin.",
      type: "radioGroup",
      required: true,
      defaultValue: "uppercase",
      options: [
        { value: "uppercase", label: "Tamamı büyük harf" },
        { value: "lowercase_bold", label: "Küçük harf ve kalın" },
      ],
    },
    {
      id: "dealer.taxNo",
      step: 1,
      group: "Taraflar",
      label: "Bayi — Vergi No",
      type: "text",
      required: true,
    },
    {
      id: "dealer.address",
      step: 1,
      group: "Taraflar",
      label: "Bayi — Adres",
      type: "longText",
      required: true,
    },
    {
      id: "dealer.representative",
      step: 1,
      group: "Taraflar",
      label: "Bayi — Yetkili Temsilci",
      type: "text",
      required: true,
    },

    // ── Step 2 — Konu ve Bölge ──
    {
      id: "productCategory",
      step: 2,
      group: "Konu ve Bölge",
      label: "Ürün / hizmet kategorisi",
      helpText:
        "Dağıtımı yapılacak ürün veya ürün ailesini 1-2 cümle ile tanımlayın. Detaylı SKU listesi EK olarak eklenir.",
      type: "longText",
      required: true,
    },
    {
      id: "distributionArea",
      step: 2,
      group: "Konu ve Bölge",
      label: "Bayilik bölgesi",
      helpText:
        "İl / ilçe / bölge / ülke düzeyinde net yazın. 'Avrupa Yakası' gibi muğlak ifadelerden kaçının.",
      type: "text",
      required: true,
    },
    {
      id: "exclusivity",
      step: 2,
      group: "Konu ve Bölge",
      label: "Münhasırlık",
      helpText:
        "Çift yönlü münhasırlık Rekabet Kurulu 2002/2 Tebliği eşiklerine tabi — kritik hacimlerde bireysel muafiyet gerekli olabilir.",
      type: "radioGroup",
      required: true,
      aiSuggestable: true,
      defaultValue: "none",
      options: [
        { value: "none", label: "Münhasırlık yok" },
        {
          value: "supplier_exclusive",
          label: "Tek yönlü (sağlayıcı münhasıran bu bayiye çalışır)",
        },
        {
          value: "mutual",
          label: "Çift yönlü (karşılıklı münhasırlık)",
        },
      ],
    },

    // ── Step 3 — Süre ──
    {
      id: "effectiveDate",
      step: 3,
      group: "Süre",
      label: "Yürürlük tarihi",
      type: "date",
      required: true,
      defaultValue: new Date().toISOString().slice(0, 10),
    },
    {
      id: "durationYears",
      step: 3,
      group: "Süre",
      label: "Sözleşme süresi (yıl)",
      type: "number",
      required: true,
      defaultValue: 2,
      validation: { min: 1, max: 10 },
    },
    {
      id: "autoRenewal",
      step: 3,
      group: "Süre",
      label: "Sözleşme otomatik uzasın mı?",
      helpText:
        "Evet ise süre sonunda 1'er yıl uzar; taraflardan biri makul ihbar süresi içinde bildirimde bulunmazsa yürürlükte kalır.",
      type: "checkbox",
      required: false,
      defaultValue: true,
    },

    // ── Step 4 — Ticari Koşullar ──
    {
      id: "pricingModel",
      step: 4,
      group: "Ticari Koşullar",
      label: "Fiyatlandırma modeli",
      aiSuggestable: true,
      helpText:
        "Yeniden satış fiyatı tespiti (RPM) 4054 m.4 uyarınca yasak; tavsiye fiyatı tavsiye olarak kalır.",
      type: "radioGroup",
      required: true,
      defaultValue: "list_discount",
      options: [
        { value: "list_discount", label: "Liste fiyatı üzerinden iskonto" },
        { value: "fixed", label: "Sabit fatura fiyatı" },
      ],
    },
    {
      id: "paymentDueDays",
      step: 4,
      group: "Ticari Koşullar",
      label: "Ödeme vadesi (gün)",
      type: "number",
      required: true,
      defaultValue: 30,
      validation: { min: 0, max: 180 },
    },
    {
      id: "minimumPurchase",
      step: 4,
      group: "Ticari Koşullar",
      label: "Minimum alım taahhüdü (TL, yıllık)",
      helpText: "Taahhüt yoksa 0 girin.",
      type: "currency",
      required: true,
      defaultValue: 0,
    },
    {
      id: "collateralType",
      step: 4,
      group: "Ticari Koşullar",
      label: "Teminat türü",
      aiSuggestable: true,
      type: "select",
      required: true,
      defaultValue: "none",
      options: [
        { value: "none", label: "Teminat yok" },
        { value: "bank_guarantee", label: "Teminat mektubu" },
        { value: "cheque", label: "Çek / senet" },
        { value: "mortgage", label: "İpotek" },
      ],
    },

    // ── Step 5 — Yükümlülükler ──
    {
      id: "reportingFrequency",
      step: 5,
      group: "Yükümlülükler",
      label: "Satış raporlama sıklığı",
      type: "select",
      required: true,
      defaultValue: "monthly",
      options: [
        { value: "monthly", label: "Aylık" },
        { value: "quarterly", label: "Çeyreklik" },
        { value: "annual", label: "Yıllık" },
      ],
    },
    {
      id: "afterSalesService",
      step: 5,
      group: "Yükümlülükler",
      label: "Satış sonrası hizmet yükümlülüğü",
      helpText:
        "Evet seçilirse 6502 TKHK çerçevesinde garanti ve servis yükümlülüğü açıkça düzenlenir.",
      type: "checkbox",
      required: false,
      defaultValue: true,
    },

    // ── Step 6 — Opsiyonel Maddeler ──
    {
      id: "hasNonCompete",
      step: 6,
      group: "Opsiyonel Maddeler",
      label: "Rekabet yasağı eklensin mi?",
      helpText:
        "2002/2 Tebliği m.5: süre max 1 yıl, coğrafi ve konu bazında sınırlı olabilir.",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "nonCompeteDuration",
      step: 6,
      group: "Opsiyonel Maddeler",
      label: "Rekabet yasağı süresi (ay)",
      type: "number",
      required: true,
      defaultValue: 12,
      dependsOn: { questionId: "hasNonCompete", equals: true },
      validation: { min: 0, max: 24 },
    },
    {
      id: "excludePortfolioCompensation",
      step: 6,
      group: "Opsiyonel Maddeler",
      label:
        "Portföy tazminatı istemlerini açıkça dışla (TTK m.122 kıyasen)",
      aiSuggestable: true,
      helpText:
        "Yargıtay içtihadı TTK m.122'yi tek satıcı/bayiye kıyasen uygular. Dışlama maddesi yoksa sözleşme sonu sürpriz tazminat doğabilir.",
      type: "checkbox",
      required: false,
      defaultValue: true,
    },
    {
      id: "hasTargetBonus",
      step: 6,
      group: "Opsiyonel Maddeler",
      label: "Hedef primi / bonus eklensin mi?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },

    // ── Step 7 — Hukuki ──
    {
      id: "jurisdictionCity",
      step: 7,
      group: "Hukuki Altyapı",
      label: "Yetkili mahkeme (il)",
      type: "text",
      required: true,
      defaultValue: "İstanbul",
    },
    {
      id: "terminationNoticeDays",
      step: 7,
      group: "Hukuki Altyapı",
      label: "Fesih ihbar süresi (gün)",
      helpText:
        "Belirsiz süreli sözleşmelerde makul fesih ihbar süresi tanınmazsa tazminat riski doğar.",
      type: "number",
      required: true,
      defaultValue: 90,
      validation: { min: 30, max: 365 },
    },
  ],

  clauses: [
    {
      id: "parties",
      order: 1,
      number: "Madde 1",
      title: "Taraflar",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [
        "supplier.name",
        "supplier.address",
        "supplier.representative",
        "dealer.name",
        "dealer.address",
        "dealer.representative",
        "effectiveDate",
      ],
      template: `İşbu Bayilik Sözleşmesi ("Sözleşme"), bir tarafta adresi {{supplier.address}} olan {{supplier.name}} ("Sağlayıcı") ile diğer tarafta adresi {{dealer.address}} olan {{dealer.name}} ("Bayi") arasında {{effectiveDate}} tarihinde akdedilmiştir. Taraflar ayrı ayrı "Taraf", birlikte "Taraflar" olarak anılacaktır. Sağlayıcı adına {{supplier.representative}}, Bayi adına {{dealer.representative}} imzaya yetkilidir.`,
    },
    {
      id: "subject",
      order: 2,
      number: "Madde 2",
      title: "Konu",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["productCategory"],
      template: `Bu Sözleşmenin konusu, Sağlayıcı'nın ürettiği veya temin ettiği {{productCategory}} ürünlerinin Bayi tarafından bu Sözleşmede belirlenen bölge, koşul ve yükümlülükler çerçevesinde satın alınarak son kullanıcılara satılmasıdır. Ürünlerin detaylı listesi ve teknik özellikleri Sözleşmenin eki (EK-1) olarak düzenlenir.`,
    },
    {
      id: "territory",
      order: 3,
      number: "Madde 3",
      title: "Bayilik Bölgesi ve Münhasırlık",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["distributionArea", "exclusivity"],
      template: `Bayinin faaliyet göstereceği bölge ("Bölge") {{distributionArea}} olarak belirlenmiştir.
{{#if exclusivity=none}}Taraflar arasında münhasırlık yoktur; Sağlayıcı aynı Bölge'de başka bayilikler açabilir ve Bayi başka sağlayıcılarla çalışabilir.{{/if}}{{#if exclusivity=supplier_exclusive}}Sağlayıcı, Sözleşme süresince bu Bölge'de Bayi dışında başka bir kişi veya kuruluşa bayilik hakkı tanımamayı taahhüt eder. Bayi, başka sağlayıcılarla çalışma hakkını saklı tutar.{{/if}}{{#if exclusivity=mutual}}Taraflar karşılıklı münhasırlık üzerinde mutabıktır: Sağlayıcı Bölge'de Bayi dışında başka bir bayilik açmaz, Bayi de Sözleşme konusu ürünlerde rakip sağlayıcılarla çalışmaz. Bu hüküm 4054 sayılı Rekabetin Korunması Hakkında Kanun ve Rekabet Kurulu 2002/2 sayılı Tebliği sınırları içinde geçerlidir.{{/if}}`,
    },
    {
      id: "term",
      order: 4,
      number: "Madde 4",
      title: "Süre",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: ["effectiveDate", "durationYears"],
      template: `Bu Sözleşme {{effectiveDate}} tarihinde yürürlüğe girer ve {{durationYears}} yıl süreyle geçerlidir.{{#if autoRenewal}} Süre sonunda Taraflardan biri Madde 14'te belirlenen ihbar süresi içinde yazılı bildirimde bulunmadığı takdirde Sözleşme 1'er yıllık dönemler halinde aynı koşullarla kendiliğinden uzar.{{/if}}`,
    },
    {
      id: "pricing",
      order: 5,
      number: "Madde 5",
      title: "Ürün ve Fiyatlandırma",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["pricingModel"],
      template: `Ürün fiyatları Sağlayıcı tarafından yayımlanan güncel liste üzerinden uygulanır. Fiyatlandırma modeli: {{pricingModel}}. Sağlayıcı, fiyat değişikliklerini en az 30 gün önceden yazılı olarak Bayiye bildirir; bildirim öncesinde verilmiş siparişler eski fiyat üzerinden karşılanır. Bayinin son kullanıcıya uygulayacağı satış fiyatını Sağlayıcı tespit edemez; bu konuda Bayiye yalnızca tavsiye fiyatı iletilebilir (4054 sayılı Kanun m.4).`,
    },
    {
      id: "orders_delivery",
      order: 6,
      number: "Madde 6",
      title: "Sipariş ve Teslim",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Bayi, ihtiyaç duyduğu ürünleri yazılı sipariş formu ile Sağlayıcıya iletir. Sağlayıcı siparişi 5 iş günü içinde onaylar ve teslim programını bildirir. Risk ve mülkiyet, ürünlerin Bayinin deposuna veya belirttiği teslim adresine ulaşmasıyla Bayiye geçer. Nakliye masrafları ve riskin geçişi hakkındaki özel düzenlemeler her siparişte ayrıca belirlenir.`,
    },
    {
      id: "payment_collateral",
      order: 7,
      number: "Madde 7",
      title: "Ödeme Koşulları ve Teminat",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["paymentDueDays", "collateralType", "minimumPurchase"],
      template: `Bayi, fatura tarihinden itibaren {{paymentDueDays}} gün içinde ödeme yapmakla yükümlüdür. Gecikme halinde TCMB avans faiz oranı uygulanır.
{{#if minimumPurchase}}Bayi, yıllık minimum {{minimumPurchase}} tutarında alım yapmayı taahhüt eder. Minimum alımın gerçekleşmemesi haklı fesih sebebi sayılır.{{/if}}
Teminat: {{collateralType}}. Teminat tutarı ve koşulları Sözleşmenin eki (EK-2) olarak düzenlenir.`,
    },
    {
      id: "dealer_obligations",
      order: 8,
      number: "Madde 8",
      title: "Bayinin Yükümlülükleri",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["reportingFrequency"],
      template: `Bayi; (a) Ürünleri yalnızca Bölge içinde ve Sözleşmede öngörülen amaçla satmayı, (b) Sağlayıcı tarafından belirlenen kalite ve sunum standartlarına uymayı, (c) yeterli stok tutmayı, (d) {{reportingFrequency}} satış raporlarını Sağlayıcıya iletmeyi, (e) Sağlayıcının marka imajını zedeleyecek davranışlardan kaçınmayı taahhüt eder.`,
    },
    {
      id: "supplier_obligations",
      order: 9,
      number: "Madde 9",
      title: "Sağlayıcının Yükümlülükleri",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Sağlayıcı; (a) Bayinin siparişlerini anlaşılan takvimde karşılamayı, (b) ürünlerin teknik bilgi ve eğitim desteğini sağlamayı, (c) pazarlama materyallerini makul ölçüde temin etmeyi, (d) ürün değişiklikleri ve geri çağırma süreçlerini Bayiye zamanında bildirmeyi taahhüt eder.`,
    },
    {
      id: "brand_usage",
      order: 10,
      number: "Madde 10",
      title: "Marka ve Logo Kullanımı",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Sağlayıcı, Bayiye Sözleşme süresince ve Bölge ile sınırlı olmak üzere markalarını, logolarını ve ticari adlarını yalnızca Ürünlerin satışı ve tanıtımı amacıyla kullanma hakkı (münhasır olmayan, devredilemez, alt lisans verilemez) tanır. Kullanım, Sağlayıcının marka kullanım kılavuzuna uygun olmak zorundadır. Sözleşmenin sona ermesiyle bu hak kendiliğinden sona erer.`,
    },
    {
      id: "after_sales",
      order: 11,
      number: "Madde 11",
      title: "Satış Sonrası Hizmet ve Garanti",
      required: false,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Bayi, ürünlerin garanti ve satış sonrası hizmetlerini 6502 sayılı Tüketicinin Korunması Hakkında Kanun ve ilgili ikincil mevzuata uygun şekilde sağlamayı taahhüt eder. Garanti kapsamındaki arızalarda Sağlayıcı, Bayinin yaptığı onarım ve değişim masraflarını önceden belirlenen oran dahilinde karşılar.`,
    },
    {
      id: "reporting_audit",
      order: 12,
      number: "Madde 12",
      title: "Raporlama ve Denetim",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: ["reportingFrequency"],
      template: `Bayi; {{reportingFrequency}} bazda satış miktarı, stok durumu ve müşteri şikayetlerini özetleyen raporları Sağlayıcıya iletir. Sağlayıcı, makul süre önceden yazılı bildirim yaparak Bayinin bu Sözleşme ile ilgili kayıt ve belgelerini yılda en fazla iki kez denetleme hakkına sahiptir.`,
    },
    {
      id: "confidentiality",
      order: 13,
      number: "Madde 13",
      title: "Gizlilik",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Taraflar, Sözleşme kapsamında paylaşılan fiyat listeleri, müşteri bilgileri, teknik veriler ve ticari sırlar dahil her türlü gizli bilgiyi yalnızca Sözleşmenin ifası için kullanmayı, üçüncü kişilere ifşa etmemeyi ve Sözleşmenin sona ermesinden sonra da 5 yıl süreyle gizli tutmayı taahhüt eder.`,
    },
    {
      id: "non_compete",
      order: 14,
      number: "Madde 14",
      title: "Rekabet Yasağı",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasNonCompete", "nonCompeteDuration"],
      template: `Bayi, Sözleşme süresince ve Sözleşmenin sona ermesinden itibaren {{nonCompeteDuration}} ay süreyle Bölge içinde Sağlayıcının rakibi olan ürünleri dağıtmamayı, pazarlamamayı ve bu yönde üçüncü kişilerle ortaklık kurmamayı taahhüt eder. Bu yasak 2002/2 sayılı Tebliğ m.5 sınırları içinde geçerlidir; makul olmayan kısıtlamalar hakim tarafından daraltılabilir.`,
    },
    {
      id: "portfolio_exclusion",
      order: 15,
      number: "Madde 15",
      title: "Portföy Tazminatı Dışlaması",
      required: false,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["excludePortfolioCompensation"],
      template: `Taraflar, bu Sözleşmenin herhangi bir sebeple sona ermesi halinde Bayinin 6102 sayılı Türk Ticaret Kanunu m.122 anlamında veya herhangi bir kıyasen uygulama çerçevesinde portföy tazminatı talep edemeyeceği hususunda açıkça mutabık kalmıştır. Bayi, Sözleşmenin sona ermesinin ticari risk kapsamında olduğunu kabul eder.`,
    },
    {
      id: "target_bonus",
      order: 16,
      number: "Madde 16",
      title: "Hedef Primi",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasTargetBonus"],
      template: `Sağlayıcı, Bayinin her takvim yılı için belirlenen satış hedefine ulaşması durumunda Sözleşme ekinde (EK-3) tanımlanan oran ve formüle göre hedef primi ödemeyi taahhüt eder. Hedef, koşulları ve ödeme takvimi her yılın başında yazılı olarak mutabık kalınır.`,
    },
    {
      id: "termination",
      order: 17,
      number: "Madde 17",
      title: "Fesih",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["terminationNoticeDays"],
      template: `Bu Sözleşme aşağıdaki hallerde sona erer: (a) Sürenin dolması ve uzatılmaması, (b) Tarafların yazılı mutabakatı, (c) Tarafların {{terminationNoticeDays}} gün önceden yazılı ihbar ile feshi, (d) Haklı sebeple derhal fesih (ödeme temerrüdü, iflas, konkordato, minimum alım taahhüdünün ihlali, marka itibarına zarar veren davranış dahil).`,
    },
    {
      id: "post_termination",
      order: 18,
      number: "Madde 18",
      title: "Sözleşme Sonrası Yükümlülükler",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Sözleşmenin sona ermesiyle Bayi; Sağlayıcıya ait tüm pazarlama materyali, etiket, ambalaj ve dijital varlıkları 30 gün içinde iade eder veya imha eder. Bayinin elinde bulunan Ürünler için Sağlayıcı, Bayinin talebi üzerine 60 gün içinde satın alma opsiyonunu kullanabilir; opsiyon kullanılmazsa Bayi stoğu satmaya devam eder ancak yeni sipariş veremez.`,
    },
    {
      id: "notice",
      order: 19,
      number: "Madde 19",
      title: "Tebligat",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Tarafların tebligat adresleri Madde 1'de belirtilen adreslerdir. Adres değişiklikleri yazılı bildirim yapılmadan geçersizdir. Tacirler arası ihtar ve ihbarlar TTK m.18/3 uyarınca noter, KEP veya iadeli taahhütlü posta yoluyla yapılır.`,
    },
    {
      id: "jurisdiction",
      order: 20,
      number: "Madde 20",
      title: "Uyuşmazlık Çözümü ve Uygulanacak Hukuk",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: ["jurisdictionCity"],
      template: `Bu Sözleşmeden doğan uyuşmazlıklarda Türk hukuku uygulanır ve {{jurisdictionCity}} Mahkemeleri ile İcra Daireleri yetkilidir.`,
    },
    {
      id: "final",
      order: 21,
      number: "Madde 21",
      title: "Son Hükümler",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Bu Sözleşme ve ekleri Taraflar arasındaki tam anlaşmayı oluşturur; önceki tüm yazılı ve sözlü mutabakatların yerine geçer. Sözleşmede yapılacak değişiklikler yazılı ve Tarafların imzasıyla geçerlidir. Herhangi bir hükmün geçersiz sayılması diğer hükümlerin geçerliliğini etkilemez. İşbu Sözleşme iki nüsha olarak düzenlenmiş ve Taraflarca imzalanmıştır.`,
    },
  ],

  warnings: [
    {
      id: "rpm_risk",
      message:
        "Fiyat modeli ne olursa olsun Bayinin son kullanıcıya satış fiyatını Sağlayıcı tespit edemez; sadece tavsiye edebilir (4054 sayılı Kanun m.4).",
      shownWhen: { questionId: "pricingModel", anyOf: ["list_discount", "fixed"] },
      severity: "info",
    },
    {
      id: "mutual_exclusivity",
      message:
        "Çift yönlü münhasırlık seçildi. Yıllık ciro ve pazar payı Rekabet Kurulu 2002/2 Tebliği eşiklerini aşıyorsa bireysel muafiyet başvurusu değerlendirilmelidir.",
      shownWhen: { questionId: "exclusivity", equals: "mutual" },
      severity: "warn",
    },
    {
      id: "portfolio_compensation",
      message:
        "Portföy tazminatı dışlama maddesi kapalı. Yargıtay TTK m.122'yi tek satıcı/bayiye kıyasen uygulayabilir; sözleşme sonu tazminat riski doğabilir.",
      shownWhen: { questionId: "excludePortfolioCompensation", equals: false },
      severity: "warn",
    },
    {
      id: "short_notice",
      message:
        "Fesih ihbar süresi 60 günden az. Belirsiz süreli veya uzun dönem ilişkilerde 'makul süre' sayılmayabilir; tazminat riski doğurur.",
      shownWhen: { questionId: "terminationNoticeDays", anyOf: [30, 45] },
      severity: "info",
    },
  ],
};
