// ============================================================
// Draft Template — Hizmet Alım Sözleşmesi
// ============================================================
//
// B2B hizmet alımları için eser (TBK m.470) veya vekâlet
// (TBK m.502) karakterinde çerçeve sözleşme. FSEK m.48 ile
// fikri mülkiyet devri, KVKK m.12 veri işleyen sıfatı ve
// bağımsız yüklenici beyanı (iş ilişkisi riski) kritik kenar
// koşulları. Avukat onayı yerini tutmaz.
// ============================================================

import type { DraftTemplate } from "../types";

export const SERVICE_TEMPLATE: DraftTemplate = {
  id: "service",
  label: "Hizmet Alım Sözleşmesi",
  description:
    "Eser veya vekâlet niteliğinde B2B hizmet alımları — danışmanlık, yazılım, tasarım, bakım — için kapsam, bedel, teslim, kabul ve IP devri.",
  category: "Hizmet",
  iconKey: "briefcase",
  estimatedMinutes: 8,
  documentTitle: "HİZMET ALIM SÖZLEŞMESİ",

  questions: [
    // ── Step 1 — Taraflar ──
    {
      id: "client.name",
      step: 1,
      group: "Taraflar",
      label: "İş Sahibi — Unvan / Ad Soyad",
      type: "text",
      required: true,
    },
    {
      id: "client.taxNo",
      step: 1,
      group: "Taraflar",
      label: "İş Sahibi — Vergi No / TC No",
      type: "text",
      required: true,
    },
    {
      id: "client.address",
      step: 1,
      group: "Taraflar",
      label: "İş Sahibi — Adres",
      type: "longText",
      required: true,
    },
    {
      id: "client.representative",
      step: 1,
      group: "Taraflar",
      label: "İş Sahibi — Yetkili Temsilci",
      type: "text",
      required: true,
    },
    {
      id: "contractor.name",
      step: 1,
      group: "Taraflar",
      label: "Yüklenici — Unvan / Ad Soyad",
      type: "text",
      required: true,
    },
    {
      id: "contractor.taxNo",
      step: 1,
      group: "Taraflar",
      label: "Yüklenici — Vergi No / TC No",
      type: "text",
      required: true,
    },
    {
      id: "contractor.address",
      step: 1,
      group: "Taraflar",
      label: "Yüklenici — Adres",
      type: "longText",
      required: true,
    },
    {
      id: "contractor.representative",
      step: 1,
      group: "Taraflar",
      label: "Yüklenici — Yetkili Temsilci",
      type: "text",
      required: true,
    },

    // ── Step 2 — İş Niteliği ──
    {
      id: "workType",
      step: 2,
      group: "İş Niteliği",
      label: "İş niteliği",
      helpText:
        "Eserde sonuç taahhüdü vardır (ayıp sorumluluğu sert); vekâlette özen borcu yeterlidir. Yanlış nitelendirme hukuki risk yaratır.",
      type: "radioGroup",
      required: true,
      defaultValue: "work",
      options: [
        {
          value: "work",
          label: "Eser sözleşmesi (sonuç taahhüdü)",
          description:
            "Belirli bir çıktının teslimi taahhüt ediliyor. Yazılım geliştirme, grafik tasarım, inşaat gibi.",
        },
        {
          value: "mandate",
          label: "Vekâlet (özen borcu)",
          description:
            "Çaba gösterilmesi yeterlidir; sonuç garantisi yoktur. Danışmanlık, yasal temsil gibi.",
        },
      ],
    },
    {
      id: "sowSummary",
      step: 2,
      group: "İş Niteliği",
      label: "İşin tanımı (SoW özeti)",
      helpText:
        "Yapılacak işi 2-5 cümle ile anlatın. Detaylı SoW sözleşmeye ek olarak (EK-1) eklenir.",
      type: "longText",
      required: true,
    },

    // ── Step 3 — Süre ve Takvim ──
    {
      id: "startDate",
      step: 3,
      group: "Süre ve Takvim",
      label: "Başlangıç tarihi",
      type: "date",
      required: true,
      defaultValue: new Date().toISOString().slice(0, 10),
    },
    {
      id: "endDate",
      step: 3,
      group: "Süre ve Takvim",
      label: "Bitiş / teslim tarihi",
      type: "date",
      required: true,
    },
    {
      id: "milestones",
      step: 3,
      group: "Süre ve Takvim",
      label: "Ara teslim (milestone) planı",
      helpText:
        "Varsa ara teslim tarihlerini ve içeriklerini listeleyin. Tek parti teslim ise boş bırakabilirsiniz.",
      type: "longText",
      required: false,
    },

    // ── Step 4 — Bedel ve Ödeme ──
    {
      id: "totalFee",
      step: 4,
      group: "Bedel ve Ödeme",
      label: "Toplam hizmet bedeli (TL)",
      type: "currency",
      required: true,
      defaultValue: 0,
    },
    {
      id: "vatIncluded",
      step: 4,
      group: "Bedel ve Ödeme",
      label: "KDV dahil mi?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "paymentPlan",
      step: 4,
      group: "Bedel ve Ödeme",
      label: "Ödeme planı",
      type: "radioGroup",
      required: true,
      defaultValue: "on_delivery",
      options: [
        { value: "upfront", label: "Peşin" },
        { value: "milestone", label: "Ara teslime bağlı taksit" },
        { value: "on_delivery", label: "Teslim üzerine tek ödeme" },
      ],
    },
    {
      id: "hasLatePenalty",
      step: 4,
      group: "Bedel ve Ödeme",
      label: "Gecikme cezası uygulansın mı?",
      helpText:
        "TBK m.179 cezai şart. Günlük tutar fahiş olursa m.182/3 uyarınca hakim tarafından indirilebilir.",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "latePenaltyDailyRate",
      step: 4,
      group: "Bedel ve Ödeme",
      label: "Günlük gecikme cezası (toplam bedelin %X'i)",
      type: "number",
      required: true,
      defaultValue: 0.1,
      dependsOn: { questionId: "hasLatePenalty", equals: true },
      validation: { min: 0, max: 5 },
    },

    // ── Step 5 — Kabul ve Ayıp ──
    {
      id: "acceptanceDays",
      step: 5,
      group: "Kabul ve Ayıp",
      label: "Kabul süresi (gün)",
      helpText:
        "Teslim sonrası bu süre içinde İş Sahibi yazılı itirazda bulunmazsa iş kabul edilmiş sayılır.",
      type: "number",
      required: true,
      defaultValue: 15,
      validation: { min: 5, max: 60 },
    },
    {
      id: "warrantyMonths",
      step: 5,
      group: "Kabul ve Ayıp",
      label: "Garanti süresi (ay)",
      helpText:
        "Eser sözleşmesinde ayıp sorumluluğu TBK m.474-478 çerçevesinde ek garanti ile uzatılabilir.",
      type: "number",
      required: true,
      defaultValue: 6,
      validation: { min: 0, max: 60 },
      dependsOn: { questionId: "workType", equals: "work" },
    },

    // ── Step 6 — Fikri Mülkiyet ──
    {
      id: "ipHandling",
      step: 6,
      group: "Fikri Mülkiyet",
      label: "Fikri mülkiyet düzenlemesi",
      helpText:
        "FSEK m.48: mali hakların devri yazılı ve hak bazında olmalı. 'Tüm haklar devredildi' genel ifadesi yetersiz sayılır.",
      type: "radioGroup",
      required: true,
      defaultValue: "transfer",
      options: [
        {
          value: "transfer",
          label: "Mali haklar İş Sahibine tam devir",
          description:
            "Çoğaltma, yayma, işleme, temsil, umuma iletim hakları süresiz devredilir. Manevi haklar devredilemez (FSEK m.14-17).",
        },
        {
          value: "exclusive_license",
          label: "Münhasır lisans (süresi belli)",
          description: "Yüklenici hak sahibi kalır; İş Sahibi tek lisans alan olur.",
        },
        {
          value: "non_exclusive_license",
          label: "Münhasır olmayan lisans",
          description:
            "Yüklenici aynı çözümü başka müşterilere de lisanslayabilir.",
        },
      ],
    },

    // ── Step 7 — Sorumluluk ve Fesih ──
    {
      id: "liabilityCapMultiplier",
      step: 7,
      group: "Sorumluluk ve Fesih",
      label: "Sorumluluk üst sınırı (hizmet bedelinin X katı)",
      helpText:
        "Standart piyasa pratiği 1-2 katı. Üst sınır konulmazsa Yüklenici zincirleme zararlardan sorumlu olabilir.",
      type: "number",
      required: true,
      defaultValue: 1,
      validation: { min: 0, max: 10 },
    },
    {
      id: "excludeIndirectDamages",
      step: 7,
      group: "Sorumluluk ve Fesih",
      label: "Dolaylı zararlar hariç tutulsun mu?",
      helpText:
        "Kar kaybı, veri kaybı, itibar zararı gibi dolaylı zararların sorumluluk dışı bırakılması piyasa pratiğidir.",
      type: "checkbox",
      required: false,
      defaultValue: true,
    },
    {
      id: "terminationNoticeDays",
      step: 7,
      group: "Sorumluluk ve Fesih",
      label: "Fesih ihbar süresi (gün)",
      type: "number",
      required: true,
      defaultValue: 30,
      validation: { min: 7, max: 90 },
    },

    // ── Step 8 — Opsiyonel Maddeler ──
    {
      id: "hasSLA",
      step: 8,
      group: "Opsiyonel Maddeler",
      label: "SLA (servis düzeyi) eklensin mi?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "hasSubcontractor",
      step: 8,
      group: "Opsiyonel Maddeler",
      label: "Alt yüklenici kullanımına izin verilsin mi?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "hasInsurance",
      step: 8,
      group: "Opsiyonel Maddeler",
      label: "Mesleki sorumluluk sigortası zorunlu olsun mu?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },
    {
      id: "hasNonSolicitation",
      step: 8,
      group: "Opsiyonel Maddeler",
      label: "Non-solicitation (çalışan/müşteri kapmama) eklensin mi?",
      type: "checkbox",
      required: false,
      defaultValue: false,
    },

    // ── Step 9 — Hukuki ──
    {
      id: "jurisdictionCity",
      step: 9,
      group: "Hukuki Altyapı",
      label: "Yetkili mahkeme (il)",
      type: "text",
      required: true,
      defaultValue: "İstanbul",
    },
  ],

  clauses: [
    {
      id: "parties",
      order: 1,
      number: "Madde 1",
      title: "Taraflar",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [
        "client.name",
        "client.address",
        "client.representative",
        "contractor.name",
        "contractor.address",
        "contractor.representative",
        "startDate",
      ],
      template: `İşbu Hizmet Alım Sözleşmesi ("Sözleşme"), bir tarafta adresi {{client.address}} olan {{client.name}} ("İş Sahibi") ile diğer tarafta adresi {{contractor.address}} olan {{contractor.name}} ("Yüklenici") arasında {{startDate}} tarihinde akdedilmiştir. Taraflar ayrı ayrı "Taraf", birlikte "Taraflar" olarak anılacaktır. İş Sahibi adına {{client.representative}}, Yüklenici adına {{contractor.representative}} imzaya yetkilidir.`,
    },
    {
      id: "subject",
      order: 2,
      number: "Madde 2",
      title: "Konu ve Kapsam",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["sowSummary", "workType"],
      template: `Bu Sözleşmenin konusu, Yüklenicinin İş Sahibi için aşağıda özetlenen ve detayları Sözleşmenin EK-1'inde düzenlenen hizmetleri ({{workType}} niteliğinde) sunmasıdır. Hizmet özeti: {{sowSummary}}`,
    },
    {
      id: "scope",
      order: 3,
      number: "Madde 3",
      title: "İş Tanımı",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Yapılacak işlerin detayı, teslim edilecek çıktılar, kabul kriterleri ve teknik özellikler Sözleşmenin EK-1'i olarak düzenlenmiş İş Tanımı (Statement of Work) belgesinde yer alır. EK-1 bu Sözleşmenin ayrılmaz parçasıdır; EK-1'de tanımlanmayan işler kapsam dışıdır ve ayrıca yazılı olarak mutabık kalınmalıdır.`,
    },
    {
      id: "schedule",
      order: 4,
      number: "Madde 4",
      title: "Süre ve Takvim",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["startDate", "endDate"],
      template: `Hizmet {{startDate}} tarihinde başlar ve {{endDate}} tarihine kadar tamamlanır.{{#if milestones}} Ara teslim takvimi: {{milestones}}{{/if}} Yüklenici mücbir sebep haricinde bu takvimin gecikmesinden sorumludur.`,
    },
    {
      id: "fee_payment",
      order: 5,
      number: "Madde 5",
      title: "Bedel ve Ödeme",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["totalFee", "paymentPlan"],
      template: `Toplam hizmet bedeli {{totalFee}} olarak belirlenmiştir (KDV {{#if vatIncluded}}dahil{{/if}}{{#if vatIncluded=false}}hariç{{/if}}). Ödeme planı: {{paymentPlan}}. Ödemeler Yüklenicinin bildireceği banka hesabına yapılır. Serbest meslek kapsamında ödenecek tutarlar için GVK m.94 uyarınca stopaj uygulanır; makbuz/fatura Yüklenici tarafından düzenlenir.`,
    },
    {
      id: "contractor_obligations",
      order: 6,
      number: "Madde 6",
      title: "Yüklenicinin Yükümlülükleri",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["workType"],
      template: `Yüklenici; (a) Hizmeti zamanında ve mesleki özenle sunmayı, (b) EK-1'deki kapsamı eksiksiz ifa etmeyi, (c) İş Sahibinin makul talimatlarına uymayı, (d) {{#if workType=work}}İşin kararlaştırılan niteliklere uygun tamamlanmasını sağlamayı{{/if}}{{#if workType=mandate}}Mesleki özen borcunu yerine getirmeyi{{/if}}, (e) gizli bilgileri korumayı taahhüt eder.`,
    },
    {
      id: "client_obligations",
      order: 7,
      number: "Madde 7",
      title: "İş Sahibinin Yükümlülükleri",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `İş Sahibi; (a) Hizmet bedelini anlaşılan takvime göre ödemeyi, (b) Yüklenicinin işini yapabilmesi için gerekli bilgi, erişim ve belgeleri makul sürede sağlamayı, (c) kabul ve onay süreçlerini geciktirmemeyi taahhüt eder.`,
    },
    {
      id: "delivery_acceptance",
      order: 8,
      number: "Madde 8",
      title: "Teslim ve Kabul",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["acceptanceDays"],
      template: `Yüklenici, her teslim için yazılı teslim tutanağı düzenler. İş Sahibi teslim tarihinden itibaren {{acceptanceDays}} gün içinde yazılı itirazlarını bildirir; aksi takdirde ilgili teslim kabul edilmiş sayılır. İtiraz halinde taraflar makul süre içinde düzeltmeler için mutabakat sağlar; mutabakat sağlanamazsa Madde 13 uyarınca uyuşmazlık çözüm süreci başlar.`,
    },
    {
      id: "warranty",
      order: 9,
      number: "Madde 9",
      title: "Ayıba Karşı Tekeffül ve Garanti",
      required: false,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["warrantyMonths"],
      template: `Yüklenici, teslim ettiği eserin kabul tarihinden itibaren {{warrantyMonths}} ay süreyle TBK m.474-478 çerçevesinde ayıba karşı tekeffül yükümlülüğü altındadır. Garanti süresi içinde ortaya çıkan ayıpları Yüklenici makul süre içinde ve ücretsiz olarak gidermekle yükümlüdür. Gizli ayıpların keşfinden itibaren İş Sahibinin ihbar süresi TBK m.477'dir.`,
    },
    {
      id: "ip_rights",
      order: 10,
      number: "Madde 10",
      title: "Fikri Mülkiyet",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["ipHandling"],
      template: `{{#if ipHandling=transfer}}Yüklenici, bu Sözleşme kapsamında ürettiği eserlerin 5846 sayılı Fikir ve Sanat Eserleri Kanunu ("FSEK") m.21-25 kapsamındaki çoğaltma, yayma, işleme, temsil ve umuma iletim mali haklarını, süre, yer ve sayı bakımından sınırsız olarak İş Sahibine devreder. FSEK m.14-17'de düzenlenen manevi haklar devredilemez; ancak Yüklenici bu hakları İş Sahibinin olağan kullanımını engelleyecek şekilde ileri sürmemeyi taahhüt eder.{{/if}}{{#if ipHandling=exclusive_license}}Yüklenici, eserlerinin mali haklarını İş Sahibine sözleşme süresi boyunca münhasır lisans ile kullandırır; hak sahipliği Yüklenicide kalır.{{/if}}{{#if ipHandling=non_exclusive_license}}Yüklenici, eserlerinin mali haklarını İş Sahibine münhasır olmayan lisans kapsamında kullandırır; Yüklenici aynı veya benzer çözümleri üçüncü kişilere de lisanslayabilir.{{/if}}
Kaynak kod veya teknik dokümantasyon üreten işlerde, bu belgeler teslim kapsamındadır ve İş Sahibine açık şekilde aktarılır.`,
    },
    {
      id: "confidentiality_kvkk",
      order: 11,
      number: "Madde 11",
      title: "Gizlilik ve Kişisel Verilerin Korunması",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: [],
      template: `Taraflar, Sözleşme kapsamında birbirine iletilen veya erişilen gizli bilgileri Sözleşmenin sona ermesinden sonra da 5 yıl süreyle korumayı taahhüt eder. Hizmet sırasında kişisel veri işleniyorsa Yüklenici 6698 sayılı KVKK m.12 kapsamında veri güvenliğini sağlar; taraflardan biri veri işleyen sıfatı taşıyorsa ayrı bir veri işleme sözleşmesi akdedilir. Veri ihlali halinde 72 saat içinde karşı Tarafa yazılı bildirim yapılır.`,
    },
    {
      id: "liability",
      order: 12,
      number: "Madde 12",
      title: "Sorumluluk ve Sınırlama",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["liabilityCapMultiplier"],
      template: `Tarafların bu Sözleşmeden doğan toplam sorumluluğu, her Taraf için bu Sözleşme kapsamında fiilen ödenen / ödenmesi gereken hizmet bedelinin {{liabilityCapMultiplier}} katı ile sınırlıdır.{{#if excludeIndirectDamages}} Kar kaybı, veri kaybı, itibar zararı, iş kaybı gibi dolaylı ve neticede doğan zararlar sorumluluk kapsamı dışındadır.{{/if}} Kasıt ve ağır ihmal hallerinde bu sınırlamalar uygulanmaz.`,
    },
    {
      id: "sla",
      order: 13,
      number: "Madde 13",
      title: "Servis Düzeyi (SLA)",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasSLA"],
      template: `Yüklenici, bu Sözleşme kapsamında sunduğu hizmete ilişkin servis düzeyi ölçütlerini, eşik değerlerini ve eşiklerin aşılması halinde uygulanacak telafi mekanizmalarını (kredi, ücretsiz uzatma vb.) Sözleşmenin EK-2'sinde detaylandırır. EK-2 bu Sözleşmenin ayrılmaz parçasıdır.`,
    },
    {
      id: "subcontractor",
      order: 14,
      number: "Madde 14",
      title: "Alt Yüklenici",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasSubcontractor"],
      template: `Yüklenici, bu Sözleşmeden doğan yükümlülüklerini yerine getirirken alt yüklenici kullanabilir. Alt yüklenicilerin eylem ve ihmalleri Yüklenicinin kendi eylem ve ihmali gibi değerlendirilir; Yüklenici İş Sahibine karşı doğrudan sorumludur. Yüklenici, alt yüklenicilerini aynı gizlilik ve veri güvenliği yükümlülüklerine tabi tutar.`,
    },
    {
      id: "insurance",
      order: 15,
      number: "Madde 15",
      title: "Mesleki Sorumluluk Sigortası",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasInsurance"],
      template: `Yüklenici, bu Sözleşme süresince ve Sözleşmenin sona ermesinden itibaren 2 yıl süreyle, EK-1'deki hizmet kapsamına uygun bir mesleki sorumluluk sigortasını yürürlükte tutar. Sigorta poliçesinin bir kopyası İş Sahibinin talebi üzerine paylaşılır.`,
    },
    {
      id: "non_solicitation",
      order: 16,
      number: "Madde 16",
      title: "Çalışan ve Müşteri Kapmama",
      required: false,
      defaultEnabled: false,
      aiEditable: true,
      requires: ["hasNonSolicitation"],
      template: `Taraflar, Sözleşme süresince ve Sözleşmenin sona ermesinden itibaren 1 yıl süreyle, karşı Tarafın çalışanlarını iş akdine teklif götürmemeyi veya müşterilerine aynı hizmet için doğrudan teklif sunmamayı taahhüt eder. Kamuya açık iş ilanları ile çalışanın kendi başvuruları bu kısıtın dışındadır.`,
    },
    {
      id: "termination",
      order: 17,
      number: "Madde 17",
      title: "Fesih",
      required: true,
      defaultEnabled: true,
      aiEditable: true,
      requires: ["terminationNoticeDays"],
      template: `Bu Sözleşme aşağıdaki hallerde sona erer: (a) Tarafların {{terminationNoticeDays}} gün önceden yazılı ihbar ile feshi, (b) İş Sahibinin TBK m.484 kapsamında cayma hakkını kullanması (yapılan iş bedelinin ödenmesi + uğranılan zararın karşılanması koşuluyla), (c) Haklı sebeple derhal fesih (ödeme temerrüdü, iflas, ağır ayıp, ihlal). Fesih halinde fiilen tamamlanmış ve teslim edilmiş çıktıların bedeli ödenir.`,
    },
    {
      id: "independent_contractor",
      order: 18,
      number: "Madde 18",
      title: "Bağımsız Yüklenici Beyanı",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Taraflar, aralarındaki ilişkinin 4857 sayılı İş Kanunu anlamında bir iş ilişkisi olmadığını, Yüklenicinin İş Sahibinin bağımlı çalışanı sayılmadığını ve Yüklenicinin kendi araç, zaman yönetimi ve yöntemleri ile bağımsız olarak çalıştığını beyan eder. Bu beyan 5510 sayılı SGK Kanunu çerçevesinde gerçek nitelik değerlendirmesini etkilemez.`,
    },
    {
      id: "notice",
      order: 19,
      number: "Madde 19",
      title: "Tebligat",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Tarafların tebligat adresleri Madde 1'de belirtilen adreslerdir. Adres değişiklikleri yazılı olarak bildirilmediği sürece, bu adreslere yapılan tebligatlar geçerli sayılır. Tacirler arası ihtar ve ihbarlar TTK m.18/3 uyarınca noter, KEP veya iadeli taahhütlü posta yoluyla yapılır.`,
    },
    {
      id: "jurisdiction",
      order: 20,
      number: "Madde 20",
      title: "Uyuşmazlık Çözümü ve Uygulanacak Hukuk",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: ["jurisdictionCity"],
      template: `Bu Sözleşmeden doğan veya Sözleşmeyle ilgili her türlü uyuşmazlıkta Türk hukuku uygulanır ve {{jurisdictionCity}} Mahkemeleri ile İcra Daireleri yetkilidir.`,
    },
    {
      id: "final",
      order: 21,
      number: "Madde 21",
      title: "Son Hükümler",
      required: true,
      defaultEnabled: true,
      aiEditable: false,
      requires: [],
      template: `Bu Sözleşme ve ekleri Taraflar arasındaki tam anlaşmayı oluşturur; önceki tüm yazılı ve sözlü mutabakatların yerine geçer. Değişiklikler yalnızca yazılı ve Tarafların imzasıyla geçerlidir. Sözleşmenin herhangi bir hükmünün geçersiz sayılması diğer hükümlerin geçerliliğini etkilemez. İşbu Sözleşme iki nüsha olarak düzenlenmiş ve Taraflarca imzalanmıştır.`,
    },
  ],

  warnings: [
    {
      id: "work_strict_liability",
      message:
        "Eser sözleşmesi seçildi. Ayıp sorumluluğu TBK m.474-478 uyarınca serttir: teslim edilen iş kararlaştırılan niteliklere sahip değilse Yüklenici onarma, fiyattan indirme veya sözleşmeden dönme borcu altındadır.",
      shownWhen: { questionId: "workType", equals: "work" },
      severity: "info",
    },
    {
      id: "mandate_effort_only",
      message:
        "Vekâlet seçildi. Yüklenici özen borcuyla yükümlü; sonuç garantisi yoktur. Sözleşmede 'teslim edilecek çıktı' tanımlıyorsanız niteleme hatalı olabilir.",
      shownWhen: { questionId: "workType", equals: "mandate" },
      severity: "info",
    },
    {
      id: "ip_generic_transfer",
      message:
        "FSEK m.48 hatırlatması: mali haklar yazılı ve hak bazında (çoğaltma, yayma, işleme, temsil, umuma iletim) devredilmelidir. 'Tüm haklar devredildi' genel ifadesi tek başına yetersiz sayılabilir.",
      shownWhen: { questionId: "ipHandling", equals: "transfer" },
      severity: "info",
    },
    {
      id: "no_liability_cap",
      message:
        "Sorumluluk üst sınırı 0 veya çok düşük. Üst sınır konulmazsa Yüklenici zincirleme zararlardan tam olarak sorumlu olur.",
      shownWhen: { questionId: "liabilityCapMultiplier", anyOf: [0] },
      severity: "warn",
    },
  ],
};
